---
- name: Deploy app container
  hosts: webservers
  gather_facts: false
  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Copy Docker image tar to remote server
      copy:
        src: /var/tmp/myapp.tar
        dest: /var/tmp/myapp.tar

    - name: Load Docker image from tar
      shell: docker load -i /var/tmp/myapp.tar

    - name: Run container
      shell: docker run -d -p 80:5000 flaskapp:latest
