name: First Actions demo
on: push
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Print date in ubuntu
        run: date 
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Print date in Windows
        run: date
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Print date in MacOS
        run: date
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Print date in ubuntu again
        run: date